[CD] Allow manual execution of the CD pipeline
Signed-off-by: Fran Mulero <francisco-jose.mulero@broadcom.com>

diff --git a/.github/workflows/cd-pipeline.yml b/.github/workflows/cd-pipeline.yml
--- a/.github/workflows/cd-pipeline.yml
+++ b/.github/workflows/cd-pipeline.yml
@@ -9,6 +9,11 @@ on: # rebuild any PRs and main branch changes
     paths:
       - 'bitnami/**'
       - '!**.md'
+  workflow_dispatch:
+    inputs:
+      chart:
+        description: "Chart to publish. Format: bitnami/<chart-name>"
+        required: true
 # Remove all permissions by default.
 permissions: {}
 jobs:
@@ -27,30 +32,37 @@ jobs:
           fetch-depth: 2 # to be able to obtain files changed in the latest commit
       - id: get-chart
         name: 'Get modified charts'
+        env:
+          WORKFLOW_INPUT: ${{ github.event.inputs != null && github.event.inputs.chart }}
         run: |
           cd charts
-          files_changed="$(git show --pretty="" --name-only)"
-          # Adding || true to avoid "Process exited with code 1" errors
-          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
-          # Using grep -c as a better alternative to wc -l when dealing with empty strings."
-          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
-          num_version_bumps="$(echo "$files_changed" | grep  "bitnami/[^/]*/Chart.yaml" | xargs git show | grep -c "+version" || true)"
-
-          if [[ "$num_charts_changed" -ne "$num_version_bumps" ]]; then
-            # Changes done in charts but version not bumped -> ERROR
-            charts_changed_str="$(echo ${charts_dirs_changed[@]})"
-            echo "error=Detected changes in charts without version bump in Chart.yaml. Charts changed: ${num_charts_changed} ${charts_changed_str}. Version bumps detected: ${num_version_bumps}" >> $GITHUB_OUTPUT
-            echo "result=fail" >> $GITHUB_OUTPUT
-          elif [[ "$num_charts_changed" -eq "1" ]]; then
-            # Changes done in only one chart -> OK
-            chart_name=$(echo "$charts_dirs_changed" | sed "s|bitnami/||g")
-            echo "chart=${chart_name}" >> $GITHUB_OUTPUT
+          if [[ -n "${WORKFLOW_INPUT}" ]] && [[ -d "${WORKFLOW_INPUT}" ]];
+            echo "chart=${WORKFLOW_INPUT}" >> $GITHUB_OUTPUT
             echo "result=ok" >> $GITHUB_OUTPUT
           else
-            # Changes done in more than chart -> FAIL
-            charts_changed_str="$(echo ${charts_dirs_changed[@]})"
-            echo "error=Changes detected in more than one chart directory: ${charts_changed_str}. The publish process will be stopped. Please create different commits for each chart." >> $GITHUB_OUTPUT
-            echo "result=fail" >> $GITHUB_OUTPUT
+            files_changed="$(git show --pretty="" --name-only)"
+            # Adding || true to avoid "Process exited with code 1" errors
+            charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
+            # Using grep -c as a better alternative to wc -l when dealing with empty strings."
+            num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
+            num_version_bumps="$(echo "$files_changed" | grep  "bitnami/[^/]*/Chart.yaml" | xargs git show | grep -c "+version" || true)"
+
+            if [[ "$num_charts_changed" -ne "$num_version_bumps" ]]; then
+              # Changes done in charts but version not bumped -> ERROR
+              charts_changed_str="$(echo ${charts_dirs_changed[@]})"
+              echo "error=Detected changes in charts without version bump in Chart.yaml. Charts changed: ${num_charts_changed} ${charts_changed_str}. Version bumps detected: ${num_version_bumps}" >> $GITHUB_OUTPUT
+              echo "result=fail" >> $GITHUB_OUTPUT
+            elif [[ "$num_charts_changed" -eq "1" ]]; then
+              # Changes done in only one chart -> OK
+              chart_name=$(echo "$charts_dirs_changed" | sed "s|bitnami/||g")
+              echo "chart=${chart_name}" >> $GITHUB_OUTPUT
+              echo "result=ok" >> $GITHUB_OUTPUT
+            else
+              # Changes done in more than chart -> FAIL
+              charts_changed_str="$(echo ${charts_dirs_changed[@]})"
+              echo "error=Changes detected in more than one chart directory: ${charts_changed_str}. The publish process will be stopped. Please create different commits for each chart." >> $GITHUB_OUTPUT
+              echo "result=fail" >> $GITHUB_OUTPUT
+            fi
           fi
       - id: show-error
         name: 'Show error'
